name: Continuous delivery

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build_and_deploy
        env:
          AWS_DEFAULT_REGION: "eu-west-1"
        run: |
          ./scripts/build_and_deploy.github.sh
