name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

env:
  REGION: ${{ secrets.AWS_REGION }}
  COR_AWS_ACCESS_KEY_ID: ${{ secrets.COR_CICD_AUTOMATION_AWS_ACCESS_KEY_ID }}
  COR_AWS_SECRET_ACCESS_KEY: ${{ secrets.COR_CICD_AUTOMATION_AWS_SECRET_ACCESS_KEY }}

jobs:
  test_src:
    name: test_src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          scripts/run_unit_test.sh
